### ISSUE TITLE
Reported WM capabilies don't reflect what mangowc implements/supports

### ISSUE THREAD

**Issue by dnkl** [DreamMaoMao/mangowc#287]
## Info

mango version: 0.10.0(7b70987)
wlroots version: 0.19.1

## Description

Mangowc reports all WM capabilities supported: window menu, fullscreen, maximize and minimize. As far as I can tell, the window/context menu isn't supported at all, and neither is minimize. So mangowc should only report maximize+fullscreen. Or only fullscreen, when `ignore_maximize:1` is set?

**Comment by DreamMaoMao** [comment]
ue to some historical reasons, minimization is disabled by default

you can enable it like this.

windowrule=ignore_minimize:0,appid:.*

**Comment by dnkl** [comment]
Thanks, though I'm mostly interested in seeing the WM capabilities reported to clients fixed, as it affects what they choose to render in their CSDs, or which key-bindings to enable by default (for example, if the WM doesn't support maximize - there's no need for an application to setup a key-binding for that).

**Comment by DreamMaoMao** [comment]
For this, I might retain the current approach because people who use tiled Windows basically do not use the minimize button on the client side, and allowing minimize requests by default would lead many applications that do not support tiling to minimize themselves without authorization.

**Comment by DreamMaoMao** [comment]
I will remove these two attribute reports when these two conditions take effect. This should solve your problem

**Comment by DreamMaoMao** [comment]
<img width="1062" height="689" alt="Image" src="https://github.com/user-attachments/assets/48aa3e8a-328f-44c4-b5d4-3c7cd0c23881" />

should fixed now. you can try it.

**Comment by dnkl** [comment]
Thanks, this works now!

**Comment by dnkl** [comment]
Actually, I still see the window/context menu capability being reported. Foot doesn't render any button for that, so you can't see any differences in the CSD, but other clients may.

```
 dbg: wayland.c:1030: xdg-toplevel: wm-capabilities=[window-menu, maximize, fullscreen]
```

**Comment by DreamMaoMao** [comment]
try again, i didn't remove menu cap befor, it is rmeoved now.

**Comment by dnkl** [comment]
Yup, it's gone now, thanks!
