### ISSUE TITLE
[Bug] Adding master to stack creates unwanted space in the bottom

### ISSUE THREAD

**Issue by jawor182** [DreamMaoMao/mangowc#487]
mango 0.10.7(0e59209)
Steps to reproduce
use master layout
make it so there are multiple windows allocated to the master side (like 20-50)
spawn some windows (for example footclient)
you should see unwanted space if the amount of clients in the master side is lower than amount of master master client set earlier

**Comment by hooxoo** [comment]
https://github.com/user-attachments/assets/1c33aa96-1de2-4d08-acf6-80422fd4d760

I also have this issue.
In the video where the empty bottom space increasing/decreasing is +1/-1 master.

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/722bc3b8-f0a0-4b5e-9e30-3cb6e4b271a9" />

Happens in Centered Tile as well.

**Comment by DreamMaoMao** [comment]
I didn't understand the issue you mentioned. Could you provide a simple replication example

**Comment by DreamMaoMao** [comment]
fixed

**Comment by TAforever** [comment]
The issue is still reproducible

https://github.com/user-attachments/assets/e7434aa5-7100-40ad-a011-62ac1b0aff02

**Comment by DreamMaoMao** [comment]
This is another issue, which has nothing to do with the number of masters. It's just the accumulation of deviations when converting floating-point numbers to integers

**Comment by DreamMaoMao** [comment]
refer:

https://github.com/DreamMaoMao/mangowc/commit/318dc85b22cb66c6bc4fcdb2b39cf8cf14cee0d3

**Comment by TAforever** [comment]
There is still a gap of about 1 pixel left; the issue most likely appeared after this commit ca48f95
